name: Docker Build and Push

on:
  repository_dispatch:
    types: [01-docker-build-push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/interview-app:latest
        
      - name: Trigger Kubernetes Apply Workflow
        uses: peter-evans/repository-dispatch@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          KUBE_CREDENTIALS_CLIENTID: ${{ secrets.KUBE_CREDENTIALS_CLIENTID }}
          KUBE_CREDENTIALS_CLIENTSECRET: ${{ secrets.KUBE_CREDENTIALS_CLIENTSECRET }}
          KUBE_CREDENTIALS_TENANTID: ${{ secrets.KUBE_CREDENTIALS_TENANTID }}
          KUBE_CREDENTIALS_SUBSCRIPTIONID: ${{ secrets.KUBE_CREDENTIALS_SUBSCRIPTIONID }}
        with:
          token: ${{ env.GITHUB_TOKEN }}
          event-type: 02-apply-deploy
          client-payload: '{"kube_credentials_clientid": "${{ env.KUBE_CREDENTIALS_CLIENTID }}","kube_credentials_clientsecret": "${{ env.KUBE_CREDENTIALS_CLIENTSECRET }}","kube_credentials_tenantid": "${{ env.KUBE_CREDENTIALS_TENANTID }}","kube_credentials_subscriptionid": "${{ env.KUBE_CREDENTIALS_SUBSCRIPTIONID }}", "docker_username": "${{ env.DOCKER_USERNAME }}"}'